# Generated by Django 3.2.5 on 2021-09-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_newuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('pincode', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='pics')),
                ('price', models.CharField(max_length=50)),
                ('edition', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='newuser',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='newuser',
            old_name='Username',
            new_name='username',
        ),
    ]
