# Generated by Django 3.2.5 on 2021-09-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210901_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='pics/')),
                ('bookname', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('edition', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.RenameField(
            model_name='newuser',
            old_name='Password',
            new_name='password',
        ),
    ]
